import Head from "next/head";

const Meta = () => {
  return (
    <Head>
      <title>Scheduler</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default Meta;
